services:
    fanuc-ethernet-cpp:
        pull_policy: build
        build:
            context: .
            network: host
        image: fanuc-ethernet-cpp:latest
        environment:
            - TERM=xterm-256color
        # All this is needed for Tracy profiling
        cap_add:
            - SYS_PTRACE
            - SYS_ADMIN
        security_opt:
            - seccomp=unconfined
        network_mode: host
        privileged: true
        pid: host
        volumes:
            - type: bind
              source: /sys/kernel/debug
              target: /sys/kernel/debug
              read_only: true